puts "The students of Herrpadurrr Academy"
puts "-----------------"
puts "Morty"
puts "Patrick Star"
puts "Cinnamon Bun"
puts "Peter Griffin"
puts "Homer Simpson"
puts "Ralph Wiggum"
puts "Cosmo"
puts "Officer Barbrady"
puts "Spongebob Squarepants"
puts "Princess Unikitty"
puts "Chris Griffin"
puts "Beavis"
puts "Lumpy Space Princess"
puts "Gir"
puts "Butters"
puts "Johnny Bravo"
puts "Pinky"
puts "Dee Dee"
