# first we print the list of students
puts "The students of Herrpadurrr Academy"
puts "-----------------"
puts "Morty"
puts "Patrick Star"
puts "Cinnamon Bun"
puts "Peter Griffin"
puts "Homer Simpson"
puts "Ralph Wiggum"
puts "Cosmo"
puts "Officer Barbrady"
puts "Spongebob Squarepants"
puts "Princess Unikitty"
puts "Chris Griffin"
puts "Beavis"
puts "Lumpy Space Princess"
puts "Gir"
puts "Butters"
puts "Johnny Bravo"
puts "Pinky"
puts "Dee Dee"
# finally, we print the total number of students
print "Overall, we have "
# it’s important that print() doesn’t add new line characters
print 18
puts " great students"
