student_count = 18
# first we print the list of students
puts "The students of Herrpadurrr Academy"
puts "-----------------"
puts "Morty"
puts "Patrick Star"
puts "Cinnamon Bun"
puts "Peter Griffin"
puts "Homer Simpson"
puts "Ralph Wiggum"
puts "Cosmo"
puts "Officer Barbrady"
puts "Spongebob Squarepants"
puts "Dick Dastardly"
puts "Chris Griffin"
puts "Scooby-Doo"
puts "Lumpy Space Princess"
puts "Shaggy"
puts "Butters"
puts "Johnny Bravo"
puts "Pinky"
puts "Dee Dee"
# finally, we print the total number of students
puts "Overall, we have #{student_count} great students"
